"""initial

Revision ID: fa6da4437779
Revises: 
Create Date: 2017-08-21 00:15:06.511763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6da4437779'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "labs"
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
